name = "esdee"
version = "1.0.0-rc1"

description = "Gleam DNS-SD discovery on Erlang"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "esdee" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
toss = ">= 1.0.0 and < 2.0.0"
glip = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
checkmark = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
